# Generated by Django 4.0.6 on 2022-07-05 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0002_remove_meetings_name_alter_categorymeeting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courspop',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
