# Generated by Django 4.0.6 on 2022-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_alter_courspop_price_alter_meetings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='is_UPCOMING_meeting',
            field=models.BooleanField(default=True),
        ),
    ]
