# Generated by Django 4.0.6 on 2022-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_siteweb_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuniversity',
            name='number_static',
            field=models.PositiveIntegerField(),
        ),
    ]
