# Generated by Django 4.0.6 on 2022-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_service_icon_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteweb',
            name='URL_site_web',
            field=models.CharField(max_length=100),
        ),
    ]
